#!/bin/csh -f

# make the C version of AutoClass
# with -tags arg, emacs tags files will be generated


cd prog

set makeflags = "OSFLAGS=-DMACOSX"
set etags_flag = -f
set sunos_solaris = ""

if ( "`/usr/bin/uname -s`" == "Darwin" ) then  # APPLE MAC OS X
  make $makeflags -f autoclass.make.macosx.gcc

else
  echo "Unrecognized operating system"
  exit
endif


mv autoclass ../autoclass

if ("X$1" != "X") then
  # compute emacs tags for autoclass
  etags $etags_flag ../autoclass.TAGS \
        globals.c init.c io-read-data.c io-read-model.c io-results.c \
        io-results-bin.c model-expander-3.c matrix-utilities.c \
	model-single-multinomial.c model-single-normal-cm.c \
	model-single-normal-cn.c model-multi-normal-cn.c \
	model-transforms.c model-update.c search-basic.c \
	search-control.c search-control-2.c \
        search-converge.c struct-class.c struct-clsf.c \
	statistics.c predictions.c \
	struct-data.c struct-matrix.c struct-model.c \
        utils.c utils-math.c \
        intf-reports.c intf-extensions.c intf-influence-values.c \
        intf-sigma-contours.c \
	prints.c getparams.c autoclass.c \
        autoclass.h getparams.h globals.h params.h fcntlcom-ac.h minmax.h
else
  # remove .o files (for distribution)
  make -f autoclass.make
endif

# back up to parent directory
cd ..

